# .github/workflows/image-build.yml
name: Build, Push & Manifest Multi-Arch Image

permissions:
  contents: read
  packages: write

# Prevent concurrent runs on the same ref
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - '.github/workflows/image-build.yml'
      - 'Dockerfile'
      - '.upstream-tag'
  pull_request:
    paths:
      - '.github/workflows/image-build.yml'
      - 'Dockerfile'
      - '.upstream-tag'
  workflow_dispatch:
  repository_dispatch:
    types: [upstream-release]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    outputs:
      image_name: ${{ steps.set-image.outputs.image_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image name
        id: set-image
        run: |
          # lowercased repo path for GHCR
          IMAGE=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          echo "image_name=$IMAGE" >> $GITHUB_OUTPUT

      - name: Register QEMU for emulation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Inject OCI labels at build time
      - name: Prepare OCI labels
        run: |
          echo "LABEL org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}" >> Dockerfile
          echo "LABEL org.opencontainers.image.revision=${GITHUB_SHA}" >> Dockerfile

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # If you prefer a PAT, uncomment below and set GHCR_TOKEN secret:
          # password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push (${{ matrix.arch }})
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true

          # per-arch tags
          tags: |
            ghcr.io/${{ steps.set-image.outputs.image_name }}:latest-${{ matrix.arch }}
            ghcr.io/${{ steps.set-image.outputs.image_name }}:${{ github.sha }}-${{ matrix.arch }}

          # scoped cache for faster incremental builds
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to:   type=gha,mode=max,scope=${{ matrix.arch }}

  manifest:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch manifest
        run: |
          IMAGE=${{ needs.build.outputs.image_name }}
          docker buildx imagetools create \
            --tag ghcr.io/$IMAGE:latest \
            --tag ghcr.io/$IMAGE:${{ github.sha }} \
            ghcr.io/$IMAGE:latest-amd64 \
            ghcr.io/$IMAGE:latest-arm64 \
            ghcr.io/$IMAGE:${{ github.sha }}-amd64 \
            ghcr.io/$IMAGE:${{ github.sha }}-arm64
